theme: jekyll-theme-minimal
title: GEFO e.V.
description: Gesellschaft ...
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Wärmepumpen
    url: waermepumpen
  - title: Batterien
    url: batterien
  - title: Photovoltaik
    url: PV
